version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://todo_user:todo_password@postgres:5432/todo_db
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todo-network

  # Prisma Studio
  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile.prisma
    container_name: todo-prisma-studio
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: postgresql://todo_user:todo_password@postgres:5432/todo_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todo-network

volumes:
  postgres_data:

networks:
  todo-network:
    driver: bridge
